version: "3.8"

networks:
  dind-net:
    driver: bridge

volumes:
  dind-certs:
  dind-data:

services:
  dind-daemon:
    image: docker:24-dind
    container_name: dind-daemon
    privileged: true
    restart: on-failure
    networks:
      dind-net:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - dind-certs:/certs/client
      - dind-data:/var/lib/docker
    ports:
      - "2376:2376"
    healthcheck:
      test: ["CMD-SHELL", "docker info > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 6

  codex:
    depends_on:
      dind-daemon:
        condition: service_healthy
    image: codex-local
    build:
      dockerfile: codex.Dockerfile
    env_file: .env
    networks:
      - dind-net
    working_dir: /app
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - dind-certs:/certs/client:ro
      - ~/.gitconfig:/etc/gitconfig:ro
      - ${WORK_DIR}:/app
      - type: bind
        source: ./jira-data
        target: /jira
        bind:
          create_host_path: true
          propagation: rshared
    restart: on-failure
    tty: true
    entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
    stdin_open: true

  jirafs:
    # Filesystem interface to JIRA; mounts JIRA issues via FUSE into the shared host directory
    build:
      context: .
      dockerfile: jirafs.Dockerfile
    env_file: .env
    networks:
      - dind-net
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    volumes:
      - type: bind
        source: ./jira-data
        target: /data
        bind:
          create_host_path: true
          propagation: shared
    command: ["--foreground", "/data"]
    restart: on-failure
    stdin_open: true
    tty: true
