version: "3.8"

networks:
  dind-net:
    driver: bridge

volumes:
  dind-certs:
  dind-data:

services:
  dind-daemon:
    image: docker:24-dind
    container_name: dind-daemon
    privileged: true
    restart: on-failure
    networks:
      dind-net:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - dind-certs:/certs/client
      - dind-data:/var/lib/docker
    healthcheck:
      test: ["CMD-SHELL", "docker info > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 6

  codex:
    depends_on:
      dind-daemon:
        condition: service_healthy
    image: codex-local
    build:
      dockerfile: codex.Dockerfile
    env_file: .env
    networks:
      - dind-net
    working_dir: /app
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_TLS_VERIFY: "1"
      DOCKER_CERT_PATH: /certs/client
      # Pass Jira CLI credentials from .env for non-interactive auth
      JIRA_CLOUD_ENDPOINT: ${JIRA_URL}
      JIRA_CLOUD_USER_EMAIL: ${JIRA_USER}
      JIRA_CLOUD_API_TOKEN: ${JIRA_API_TOKEN}
    volumes:
      - dind-certs:/certs/client:ro
      - ~/.gitconfig:/etc/gitconfig:ro
      - ${WORK_DIR}:/app
    restart: on-failure
    tty: true
    stdin_open: true
