services:
  codex:
    user: 1000:1000
    image: codex-local
    build:
      dockerfile: codex.Dockerfile
    env_file: .env
    working_dir: /app
    volumes:
      - ./:/app
      - /etc/passwd:/etc/passwd:ro

